### PR TITLE
Gripper and roscontrol fix

### PR DESCRIPTION
**Pull request by k-okada**
@TheDash 

Why you did not merge this wonderful feature to the main branch?

@cretaceous-creature, @cretaceous-creature

### CODE REVIEW

**Comment by cretaceous-creature** [comment]
Okada sensei,
         I also don't know why the pr2 gripper fail to work with the
controller.
         Thank you very much for telling me how to fix it.

2016年1月13日水曜日、Kei Okadanotifications@github.comさんは書きました:

**Comment by UltronDestroyer** [comment]
I ran out of time on this project.. and now its been so long I'm not sure where i was going with it lol

**Comment by paulbovbel** [comment]
I don't think this PR is consistent with the current code base, but I'd be happy to review and merge changes to the URDF (and the primary simulation bringup via husky_playpen/spawn_husly.launch) that enable a gripper without breaking anything else.

@ibaranov-cp what's the current story with ros-control and the UR5. Do you end up running two controller managers? We can probably replicate that approach in sim.

**Comment by ibaranov-cp** [comment]
I am unsure about this PR, but my version for ridgeback + UR10 was using one for each.
However, I am far from an expert on this, so better version are definitely possible.

**Comment by paulbovbel** [comment]
Composable robots is not a feature of ros_control, so needing two controller managers with different rosgraph endpoints is reasonable. Tt was never implemented in this branch, since @TheDash worked on it prior to hardware-UR supporting ros_control (ur modern driver).

**Comment by k-okada** [comment]
moved to #24

**Pull request closed without merging**
