### PR TITLE
Respect env var setup similar to husky_description

### PR DESCRIPTION
**Pull request by UltronDestroyer**

### CODE REVIEW

**Comment by tonybaltovski** [comment]
Duplicate of #31?

**Comment by UltronDestroyer** [comment]
Editing through the web interface doesn't (or at least I don't know how to..) allow to add multiple commits into a PR via the edit fn. Anyways, the 2 PR's address the 2 different launch files, husky_empty_world and husky_playpen

**Review by tonybaltovski — APPROVED** [review]

**Comment by tonybaltovski** [comment]
Ah, LGTM.  If you commit to the same branch, it will be in the same PR.

**Comment by UltronDestroyer** [comment]
Figured that was the case.

**Pull request merged**
